name: CI

on: [push, pull_request]

jobs:
  windows-latest:
    name: Windows and lint
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: 17
          cache: 'maven'
      - name: Cache Node dependencies
        id: cache-node-dependencies
        uses: actions/cache@v3
        with:
          path: |
            react-client/.yarn
            react-client/node
            react-client/node_modules
          key: node-dependencies-${{ hashFiles('yarn.lock') }}
      - name: Run linter and tests
        run: mvn package -P windows
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: Artifact
          path: target/UMS-setup.exe
